# Generated by Django 3.2.4 on 2021-07-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ids',
            new_name='identification',
        ),
    ]
